### ISSUE TITLE
theres nothing in clients even when i have a game open

### ISSUE THREAD

**Issue by lunarnaut3** [Riz-ve/Xeno#16]
do i have to use the microsoft store one or is bloxstrap fine
![image](https://github.com/user-attachments/assets/49ef44b6-86a7-4b25-a348-307b7a03a221)

**Comment by Riz-ve** [comment]
should try using bloxstrap it was fixed for most people

**Comment by MrRepyhon** [comment]
> should try using bloxstrap it was fixed for most people

Still, i have bloxstrap ver 2.5.3 & latest version and its still won't working

**Comment by Riz-ve** [comment]
make sure that the exe file name for Roblox is "RobloxPlayerBeta.exe"

**Comment by MrRepyhon** [comment]
> make sure that the exe file name for Roblox is "RobloxPlayerBeta.exe"

It is Indeed RobloxPlayerBeta.exe but sometime it wont executing.
